### ISSUE TITLE
"Paste Database" is not available

### ISSUE THREAD

**Issue by lauff** [nosqlbooster/feedback#17]
**Describe the bug**
I need to copy the database, but "Paste Database" is not available.

**To Reproduce**
As described, I first select "Copy Database" on the source. After that, I try to select "Paste Database" on the target DB, but this is not available.

**Expected behavior**
"Paste Database" to be available.

**Screenshots**
![Screenshot 2023-04-22 075945](https://user-images.githubusercontent.com/150673/233765823-d3e2d4c7-6bd3-4635-b45e-477956fc3046.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**NoSQLBooster Version**
8.0.8

**Comments**
Selecting the individual Collections, copying them and pasting works.

**Comment by qinghai5878** [comment]
Please select the connection node first.

![image](https://github.com/nosqlbooster/feedback/assets/124222871/fba52853-24e1-4dea-a934-6308b6d213e0)
